env:
  requirements: '["pandas-datareader==0.9.0"]'
on:
  schedule:
    # runs at 23:00 JST every day
    - cron:  '00 14 * * *'
jobs:
  build_report:
    runs-on: ubuntu-latest
    name: Run Datapane stock report every day at 11 pm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: datapane/build-action@v2
        with:
          script: "StockReport.py"
          token: ${{ secrets.dpToken }}
          requirements: "${{ env.requirements}}"
